#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v4
# autospec commit: 1ab68ca
#
Name     : girara
Version  : 0.4.3
Release  : 10
URL      : https://github.com/pwmt/girara/archive/0.4.3/girara-0.4.3.tar.gz
Source0  : https://github.com/pwmt/girara/archive/0.4.3/girara-0.4.3.tar.gz
Summary  : User interface library focused on simplicity and minimalism
Group    : Development/Tools
License  : Zlib
Requires: girara-lib = %{version}-%{release}
Requires: girara-license = %{version}-%{release}
Requires: girara-locales = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : doxygen
BuildRequires : glib-dev
BuildRequires : json-glib-dev
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(json-c)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : xvfb-run
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
girara is a library that implements a user interface that focuses on simplicity
and minimalism. It consists of three main components: The view is a widget that
represents the actual application (e.g.: a web site or a document). The input
bar is used to execute commands of the application, while the status bar
notifies the user with current information. It is designed to replace and the
enhance the user interface that is used by zathura.

%package dev
Summary: dev components for the girara package.
Group: Development
Requires: girara-lib = %{version}-%{release}
Provides: girara-devel = %{version}-%{release}
Requires: girara = %{version}-%{release}

%description dev
dev components for the girara package.


%package lib
Summary: lib components for the girara package.
Group: Libraries
Requires: girara-license = %{version}-%{release}

%description lib
lib components for the girara package.


%package license
Summary: license components for the girara package.
Group: Default

%description license
license components for the girara package.


%package locales
Summary: locales components for the girara package.
Group: Default

%description locales
locales components for the girara package.


%prep
%setup -q -n girara-0.4.3
cd %{_builddir}/girara-0.4.3
pushd ..
cp -a girara-0.4.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1710192512
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/girara
cp %{_builddir}/girara-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/girara/b2b3cc2f3e6cb8dc9696d50700ebe1154f85101f || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang libgirara-gtk3-4
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/girara/callbacks.h
/usr/include/girara/commands.h
/usr/include/girara/completion.h
/usr/include/girara/config.h
/usr/include/girara/datastructures.h
/usr/include/girara/entry.h
/usr/include/girara/girara-version.h
/usr/include/girara/girara.h
/usr/include/girara/input-history.h
/usr/include/girara/log.h
/usr/include/girara/macros.h
/usr/include/girara/session.h
/usr/include/girara/settings.h
/usr/include/girara/shortcuts.h
/usr/include/girara/statusbar.h
/usr/include/girara/template.h
/usr/include/girara/types.h
/usr/include/girara/utils.h
/usr/lib64/libgirara-gtk3.so
/usr/lib64/pkgconfig/girara-gtk3.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libgirara-gtk3.so.4.0
/usr/lib64/libgirara-gtk3.so.4
/usr/lib64/libgirara-gtk3.so.4.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/girara/b2b3cc2f3e6cb8dc9696d50700ebe1154f85101f

%files locales -f libgirara-gtk3-4.lang
%defattr(-,root,root,-)

